plugins:
    - "stylelint-scss"
extends:
    - "stylelint-config-standard"
    - "stylelint-config-recommended"
rules:
    indentation: 4
    at-rule-no-unknown: null
    scss/at-rule-no-unknown: true
