const data = [
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.anahuac.mx/"],
        name: "Universidad Anáhuac",
        alpha_two_code: "MX",
        domains: ["anahuac.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://bajio.delasalle.edu.mx/"],
        name: "Universidad de La Salle, Bajío",
        alpha_two_code: "MX",
        domains: ["bajio.delasalle.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.buap.mx/"],
        name: "Benemerita Universidad Autónoma de Puebla",
        alpha_two_code: "MX",
        domains: ["buap.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.campusleon.ugto.mx/"],
        name: "Universidad de Guanajuato, Campus León",
        alpha_two_code: "MX",
        domains: ["campusleon.ugto.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ceti.mx/"],
        name: "Centro de Enseñanza Técnica Industrial",
        alpha_two_code: "MX",
        domains: ["ceti.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.cetys.mx/"],
        name: "CETYS Universidad",
        alpha_two_code: "MX",
        domains: ["cetys.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ceu.edu.mx/"],
        name: "Centro de Estudios Universitarios Monterrey",
        alpha_two_code: "MX",
        domains: ["ceu.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ceunix.com.mx/"],
        name: "Centro Universitario Ixtlahuaca",
        alpha_two_code: "MX",
        domains: ["ceunix.com.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ceux.mx/"],
        name: "Centro de Estudios Universitarios Xochicalco",
        alpha_two_code: "MX",
        domains: ["ceux.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.champagnat.edu.mx/"],
        name: "Universidad Champagnat",
        alpha_two_code: "MX",
        domains: ["champagnat.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.chapingo.mx/"],
        name: "Universidad Autónoma de Chapingo",
        alpha_two_code: "MX",
        domains: ["chapingo.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.colmex.mx/"],
        name: "El Colegio de México",
        alpha_two_code: "MX",
        domains: ["colmex.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.cuauhtemoc.edu.mx/"],
        name: "Universidad Cuauhtémoc",
        alpha_two_code: "MX",
        domains: ["cuauhtemoc.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://cueyatl.uam.mx/"],
        name: "Universidad Autónoma Metropolitana - Xochimilco",
        alpha_two_code: "MX",
        domains: ["cueyatl.uam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.dgit.gob.mx/"],
        name: "Dirección General de Institutos Tecnológicos",
        alpha_two_code: "MX",
        domains: ["dgit.gob.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ebc.mx/"],
        name: "Escuela Bancaria y Comercial",
        alpha_two_code: "MX",
        domains: ["ebc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.enes.unam.mx/"],
        name: "Escuela Nacional de Estudios Superiores Unidad León",
        alpha_two_code: "MX",
        domains: ["enes.unam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.frayluca.edu.mx/"],
        name: "Universidad Fray Luca Paccioli",
        alpha_two_code: "MX",
        domains: ["frayluca.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://hispano.edu.mx/"],
        name: "Universidad Hispanoamericana",
        alpha_two_code: "MX",
        domains: ["hispano.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.i.edu.mx/"],
        name: "Universidad Itaca",
        alpha_two_code: "MX",
        domains: ["i.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ipn.edu.mx/"],
        name: "Instituto Politécnico Nacional",
        alpha_two_code: "MX",
        domains: ["ipn.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itam.mx/"],
        name: "Instituto Tecnológico Autonómo de México",
        alpha_two_code: "MX",
        domains: ["itam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ita.mx/"],
        name: "Instituto Tecnológico de Aguascalientes",
        alpha_two_code: "MX",
        domains: ["ita.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itc.mx/"],
        name: "Instituto Tecnológico de Celaya",
        alpha_two_code: "MX",
        domains: ["itc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itdurango.edu.mx/"],
        name: "Instituto Tecnologico de Durango",
        alpha_two_code: "MX",
        domains: ["itdurango.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itesm.mx/"],
        name:
            "Instituto Tecnológico y de Estudios Superiores de Monterrey (ITESM)",
        alpha_two_code: "MX",
        domains: ["itesm.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.iteso.mx/"],
        name: "Instituto Tecnológico y de Estudios Superiores de Occidente",
        alpha_two_code: "MX",
        domains: ["iteso.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itleon.edu.mx/"],
        name: "Instituto Tecnológico de León",
        alpha_two_code: "MX",
        domains: ["itleon.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itmina.edu.mx/"],
        name: "Instituto Tecnologico de Minatitlan",
        alpha_two_code: "MX",
        domains: ["itmina.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itmorelia.edu.mx/"],
        name: "Instituto Tecnológico de Morelia",
        alpha_two_code: "MX",
        domains: ["itmorelia.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itq.edu.mx/"],
        name: "Instituto Tecnológico de Querétaro",
        alpha_two_code: "MX",
        domains: ["itq.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itslp.edu.mx/"],
        name: "Instituto Tecnológico de San Luis Potosí",
        alpha_two_code: "MX",
        domains: ["itslp.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itson.mx/"],
        name: "Instituto Tecnológico de Sonora",
        alpha_two_code: "MX",
        domains: ["itson.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.iztapalapa.uam.mx/"],
        name: "Universidad Autónoma Metropolitana - Iztapalapa",
        alpha_two_code: "MX",
        domains: ["iztapalapa.uam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.lef.upn.mx/"],
        name: "Universidad Pedagógica Nacional, Unidad León",
        alpha_two_code: "MX",
        domains: ["lef.upn.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.leon.uia.mx/"],
        name: "Universidad Iberoamericana, Campus León",
        alpha_two_code: "MX",
        domains: ["leon.uia.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://members.rotfl.com/uvp/"],
        name: "Universidad del Valle de Puebla",
        alpha_two_code: "MX",
        domains: ["members.rotfl.com"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.motolinia.com.mx/"],
        name: "Universidad Motolinía del Pedregal",
        alpha_two_code: "MX",
        domains: ["motolinia.com.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.olmeca.edu.mx/"],
        name: "Universidad Olmeca",
        alpha_two_code: "MX",
        domains: ["olmeca.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.poligto.edu.mx/"],
        name: "Politécnico de Guanajuato",
        alpha_two_code: "MX",
        domains: ["poligto.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.reduaeh.mx/"],
        name: "Universidad Autónoma del Estado de Hidalgo",
        alpha_two_code: "MX",
        domains: ["reduaeh.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.reduaz.mx/"],
        name: "Universidad Autónoma de Zacatecas",
        alpha_two_code: "MX",
        domains: ["reduaz.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.secupv.org/"],
        name: "Universidad Pedagógica Veracruzana",
        alpha_two_code: "MX",
        domains: ["secupv.org"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.tecbc.mx/"],
        name: "Tecnologico de Baja California, Universidad",
        alpha_two_code: "MX",
        domains: ["tecbc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.tepeyac.edu.mx/"],
        name: "Universidad del Tepeyac",
        alpha_two_code: "MX",
        domains: ["tepeyac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ties.com.mx/"],
        name: "Instituto de Estudios Superiores de la Sierra",
        alpha_two_code: "MX",
        domains: ["ties.com.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaaan.mx/"],
        name: 'Universidad Autónoma Agraria "Antonio Narro"',
        alpha_two_code: "MX",
        domains: ["uaaan.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaa.mx:8001/"],
        name: "Universidad Autónoma de Aguascalientes",
        alpha_two_code: "MX",
        domains: ["uaa.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uabc.mx/"],
        name: "Universidad Autónoma de Baja California",
        alpha_two_code: "MX",
        domains: ["uabc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uabcs.mx/"],
        name: "Universidad Autónoma de Baja California Sur",
        alpha_two_code: "MX",
        domains: ["uabcs.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uabjo.mx/"],
        name: 'Universidad Autónoma "Benito Juárez" de Oaxaca',
        alpha_two_code: "MX",
        domains: ["uabjo.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uacam.mx/"],
        name: "Universidad Autónoma de Campeche",
        alpha_two_code: "MX",
        domains: ["uacam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uach.mx/"],
        name: "Universidad Autónoma de Chihuahua",
        alpha_two_code: "MX",
        domains: ["uach.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://itsncg.edu.mx/"],
        name: "Instituto Tecnológico Superior de Nuevo Casas Grandes",
        alpha_two_code: "MX",
        domains: ["itsncg.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uacj.mx/"],
        name: "Universidad Autónoma de Ciudad Juárez",
        alpha_two_code: "MX",
        domains: ["uacj.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uacm.edu.mx/"],
        name: "Universidad Autónoma de la Ciudad de México",
        alpha_two_code: "MX",
        domains: ["uacm.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uadec.mx/"],
        name: "Universidad Autónoma de Coahuila",
        alpha_two_code: "MX",
        domains: ["uadec.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uad.edu.mx/"],
        name: "Universidad Autonoma  de Durango",
        alpha_two_code: "MX",
        domains: ["uad.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uady.mx/"],
        name: "Universidad Autónoma de Yucatán",
        alpha_two_code: "MX",
        domains: ["uady.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaed.edu.mx/"],
        name: "Universidad Autonoma España de Durango",
        alpha_two_code: "MX",
        domains: ["uaed.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaemex.mx/"],
        name: "Universidad Autónoma del Estado de México",
        alpha_two_code: "MX",
        domains: ["uaemex.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaem.mx/"],
        name: "Universidad Autónoma del Estado de Morelos",
        alpha_two_code: "MX",
        domains: ["uaem.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaf.mx/"],
        name: "Universidad Autónoma de Fresnillo",
        alpha_two_code: "MX",
        domains: ["uaf.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uag.mx/"],
        name: "Universidad Autónoma de Guadalajara",
        alpha_two_code: "MX",
        domains: ["uag.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uagro.mx/"],
        name: "Universidad Autónoma de Guerrero",
        alpha_two_code: "MX",
        domains: ["uagro.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ual.mx/"],
        name: "Universidad Autónoma de la Laguna",
        alpha_two_code: "MX",
        domains: ["ual.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uam.mx/"],
        name: "Universidad Autónoma Metropolitana",
        alpha_two_code: "MX",
        domains: ["uam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uane.edu.mx/"],
        name: "Universidad Autónoma del Noreste",
        alpha_two_code: "MX",
        domains: ["uane.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uanl.mx/"],
        name: "Universidad Autónoma de Nuevo León",
        alpha_two_code: "MX",
        domains: ["uanl.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uan.mx/"],
        name: "Universidad Autónoma de Nayarit",
        alpha_two_code: "MX",
        domains: ["uan.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaq.mx/"],
        name: "Universidad Autónoma de Querétaro",
        alpha_two_code: "MX",
        domains: ["uaq.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaslp.mx/"],
        name: "Universidad Autónoma de San Luis Potosí",
        alpha_two_code: "MX",
        domains: ["uaslp.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uas.mx/"],
        name: "Universidad Anáhuac del Sur",
        alpha_two_code: "MX",
        domains: ["uas.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uasnet.mx/"],
        name: "Universidad Autónoma de Sinaloa",
        alpha_two_code: "MX",
        domains: ["uasnet.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uat.mx/"],
        name: "Universidad Autónoma de Tamaulipas",
        alpha_two_code: "MX",
        domains: ["uat.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uatx.mx/"],
        name: "Universidad Autónoma de Tlaxcala",
        alpha_two_code: "MX",
        domains: ["uatx.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ubac.edu.mx/"],
        name: "Universidad del Bajío",
        alpha_two_code: "MX",
        domains: ["ubac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ucem.edu.mx/"],
        name: "Universidad del Centro de México",
        alpha_two_code: "MX",
        domains: ["ucem.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uclah.edu.mx/"],
        name: "Universidad Cientifica Latinoamericana de Hidalgo",
        alpha_two_code: "MX",
        domains: ["uclah.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ucol.mx/"],
        name: "Universidad de Colima",
        alpha_two_code: "MX",
        domains: ["ucol.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udec.edu.mx/"],
        name: "Universidad de Celaya",
        alpha_two_code: "MX",
        domains: ["udec.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udeci.edu.mx/"],
        name: "Universidad de Cuautitlan Izcalli",
        alpha_two_code: "MX",
        domains: ["udeci.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udeh.edu.mx/"],
        name: "Universidad de Hermosillo",
        alpha_two_code: "MX",
        domains: ["udeh.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udem.edu.mx/"],
        name: "Universidad de Monterrey",
        alpha_two_code: "MX",
        domains: ["udem.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udesanmiguel.edu.mx/"],
        name: "Universidad de San Miguel",
        alpha_two_code: "MX",
        domains: ["udesanmiguel.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udg.mx/"],
        name: "Universidad de Guadalajara",
        alpha_two_code: "MX",
        domains: ["udg.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udla.mx/"],
        name: "Universidad de las Américas",
        alpha_two_code: "MX",
        domains: ["udla.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udlap.mx/"],
        name: "Universidad de las Américas - Puebla",
        alpha_two_code: "MX",
        domains: ["udlap.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udo.mx/"],
        name: "Universidad de Occidente",
        alpha_two_code: "MX",
        domains: ["udo.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udv.edu.mx/"],
        name: "Universidad Don Vasco",
        alpha_two_code: "MX",
        domains: ["udv.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ufm.edu.mx/"],
        name: "Universidad Franciscana de México",
        alpha_two_code: "MX",
        domains: ["ufm.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ufram.edu.mx/"],
        name: "Universidad Franco-Mexicana",
        alpha_two_code: "MX",
        domains: ["ufram.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ugto.mx/"],
        name: "Universidad de Guanajuato",
        alpha_two_code: "MX",
        domains: ["ugto.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uia.mx/"],
        name: "Universidad Iberoamericana",
        alpha_two_code: "MX",
        domains: ["uia.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uic.edu.mx/"],
        name: "Universidad Intercontinental",
        alpha_two_code: "MX",
        domains: ["uic.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uileon.edu.mx/"],
        name: "Universidad Insurgentes Plantel León",
        alpha_two_code: "MX",
        domains: ["uileon.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ujat.mx/"],
        name: "Universidad Juárez Autónoma de Tabasco",
        alpha_two_code: "MX",
        domains: ["ujat.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ujed.mx/"],
        name: "Universidad Juárez del Estado de Durango",
        alpha_two_code: "MX",
        domains: ["ujed.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ujsierra.mx/"],
        name: "Universidad Justo Sierra",
        alpha_two_code: "MX",
        domains: ["ujsierra.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ula.edu.mx/"],
        name: "Universidad Latinoamericana",
        alpha_two_code: "MX",
        domains: ["ula.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ulsab.edu.mx/"],
        name: "Universidad Lasallista Benavente",
        alpha_two_code: "MX",
        domains: ["ulsab.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ulsac.edu.mx/"],
        name: "Universidad La Salle Cuernavaca",
        alpha_two_code: "MX",
        domains: ["ulsac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ulsa.edu.mx/"],
        name: "Universidad La Salle",
        alpha_two_code: "MX",
        domains: ["ulsa.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umad.edu.mx/"],
        name: "Universidad Madero",
        alpha_two_code: "MX",
        domains: ["umad.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uman.edu.mx/"],
        name: "Universidad México Americana del Norte",
        alpha_two_code: "MX",
        domains: ["uman.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umar.mx/"],
        name: "Universidad del Mar",
        alpha_two_code: "MX",
        domains: ["umar.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umich.mx/"],
        name: "Universidad Michoacana de San Nicolás de Hidalgo",
        alpha_two_code: "MX",
        domains: ["umich.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umi.edu.mx/"],
        name: "Universidad México Internacional",
        alpha_two_code: "MX",
        domains: ["umi.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umla.edu.mx/"],
        name: "Universidad Metropolitana Latin Campus",
        alpha_two_code: "MX",
        domains: ["umla.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umm.edu.mx/"],
        name: "Universidad Metropolitana de Monterrey",
        alpha_two_code: "MX",
        domains: ["umm.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umne.edu.mx/"],
        name: "Universidad Mexicana del Noreste",
        alpha_two_code: "MX",
        domains: ["umne.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umontemorelos.edu.mx/"],
        name: "Universidad de Montemorelos",
        alpha_two_code: "MX",
        domains: ["umontemorelos.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umsa.edu.mx/"],
        name: "Universidad Mesoamericana de San Agustín",
        alpha_two_code: "MX",
        domains: ["umsa.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unacar.mx/"],
        name: "Universidad Autónoma del Carmen",
        alpha_two_code: "MX",
        domains: ["unacar.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unach.mx/"],
        name: "Universidad Autónoma de Chiapas",
        alpha_two_code: "MX",
        domains: ["unach.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unam.mx/"],
        name: "Universidad Nacional Autónoma de México",
        alpha_two_code: "MX",
        domains: ["unam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.un.edu.mx/"],
        name: "Universidad del Norte",
        alpha_two_code: "MX",
        domains: ["un.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.une.edu.mx/"],
        name: "Universidad del Noreste",
        alpha_two_code: "MX",
        domains: ["une.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unes.edu.mx/"],
        name: "Universidad España de Durango",
        alpha_two_code: "MX",
        domains: ["unes.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unicach.edu.mx/"],
        name: "Universidad de Ciencias y Artes de Chiapas",
        alpha_two_code: "MX",
        domains: ["unicach.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unica.edu.mx/"],
        name: "Universidad de Comunicación Avanzada",
        alpha_two_code: "MX",
        domains: ["unica.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unikino.mx/"],
        name: "Universidad Kino",
        alpha_two_code: "MX",
        domains: ["unikino.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unimayab.edu.mx/"],
        name: "Universidad del Mayab",
        alpha_two_code: "MX",
        domains: ["unimayab.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unimex.edu.mx/"],
        name: "Universidad Mexicana",
        alpha_two_code: "MX",
        domains: ["unimex.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unitec.mx/"],
        name: "Universidad Tecnológica de México",
        alpha_two_code: "MX",
        domains: ["unitec.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.univa.mx/"],
        name: "Universidad del Valle de Atemajac",
        alpha_two_code: "MX",
        domains: ["univa.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.univas.edu.mx/"],
        name: "Universidad Jóse Vasconcelos",
        alpha_two_code: "MX",
        domains: ["univas.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.univchapultepec.edu.mx/"],
        name: "Universidad Chapultepéc",
        alpha_two_code: "MX",
        domains: ["univchapultepec.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.universidaddeleon.edu.mx/"],
        name: "Universidad de León",
        alpha_two_code: "MX",
        domains: ["universidaddeleon.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.universidadlaconcordia.edu.mx/"],
        name: "Universidad la Concordia",
        alpha_two_code: "MX",
        domains: ["universidadlaconcordia.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.universidadmotolinia.edu.mx/"],
        name: "Universidad Motolinía del Pedegral",
        alpha_two_code: "MX",
        domains: ["universidadmotolinia.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.universidadsalesiana.edu.mx/"],
        name: "Universidad Salesiana",
        alpha_two_code: "MX",
        domains: ["universidadsalesiana.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.univillarica.mx/"],
        name: "Universidad Autónoma de Veracruz Villa Rica",
        alpha_two_code: "MX",
        domains: ["univillarica.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unla.edu.mx/"],
        name: "Universidad Latina",
        alpha_two_code: "MX",
        domains: ["unla.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.un.mx/"],
        name: "Universidad de Norteamerica",
        alpha_two_code: "MX",
        domains: ["un.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uno.mx/"],
        name: "Universidad del Noroeste",
        alpha_two_code: "MX",
        domains: ["uno.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unum.edu.mx/"],
        name: "Universidad Nuevo Mundo",
        alpha_two_code: "MX",
        domains: ["unum.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uom.edu.mx/"],
        name: "Universidad Obrera de Mexico",
        alpha_two_code: "MX",
        domains: ["uom.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.upaep.mx/"],
        name: "Universidad Popular Autonóma del Estado de Puebla",
        alpha_two_code: "MX",
        domains: ["upaep.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.upiig.ipn.mx/"],
        name: "Instituto Politécnico Nacional, Campus Guanajuato",
        alpha_two_code: "MX",
        domains: ["upiig.ipn.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.up.mx/"],
        name: "Universidad Panamericana",
        alpha_two_code: "MX",
        domains: ["up.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.upn.mx/"],
        name: "Universidad Pedagógica Nacional",
        alpha_two_code: "MX",
        domains: ["upn.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uqroo.mx/"],
        name: "Universidad de Quintana Roo",
        alpha_two_code: "MX",
        domains: ["uqroo.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.urmh.edu.mx/"],
        name: "Universidad Regional Miguel Hidalgo",
        alpha_two_code: "MX",
        domains: ["urmh.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ur.mx/"],
        name: "Universidad Regiomontana",
        alpha_two_code: "MX",
        domains: ["ur.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.urse.edu.mx/"],
        name: "Universidad Regional del Sureste",
        alpha_two_code: "MX",
        domains: ["urse.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.usac.edu.mx/"],
        name: "Universidad de la Sierra A.C.",
        alpha_two_code: "MX",
        domains: ["usac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.usb.edu.mx/"],
        name: "Universidad Simón Bolivar",
        alpha_two_code: "MX",
        domains: ["usb.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.usf.com.mx/"],
        name: "Universidad Santa Fe",
        alpha_two_code: "MX",
        domains: ["usf.com.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uson.mx/"],
        name: "Universidad de Sonora",
        alpha_two_code: "MX",
        domains: ["uson.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.utm.mx/"],
        name: "Universidad Tecnologica de la Mixteca",
        alpha_two_code: "MX",
        domains: ["utm.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.utneza.edu.mx/"],
        name: "Universidad Tecnologica de Nezahualcoyotl",
        alpha_two_code: "MX",
        domains: ["utneza.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uvb.edu.mx/"],
        name: "Universidad del Valle del Bravo",
        alpha_two_code: "MX",
        domains: ["uvb.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uvg1.net/"],
        name: "Universidad Valle del Grijalva",
        alpha_two_code: "MX",
        domains: ["uvg1.net"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uvmnet.edu/"],
        name: "Universidad del Valle de México",
        alpha_two_code: "MX",
        domains: ["uvmnet.edu"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uv.mx/"],
        name: "Universidad Veracruzana",
        alpha_two_code: "MX",
        domains: ["uv.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uvt.edu.mx/"],
        name: "Universidad del Valle de Toluca",
        alpha_two_code: "MX",
        domains: ["uvt.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uxac.edu.mx/"],
        name: "Universidad Xicotepetl",
        alpha_two_code: "MX",
        domains: ["uxac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ver.ucc.mx/"],
        name: "Universidad Cristóbal Colón",
        alpha_two_code: "MX",
        domains: ["ver.ucc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.westhill.edu.mx/"],
        name: "Westhill University",
        alpha_two_code: "MX",
        domains: ["westhill.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["https://azc.uam.mx/"],
        name: "Universidad Autónoma Metropolitana - Azcapotzalco",
        alpha_two_code: "MX",
        domains: ["azc.uam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itsoeh.edu.mx/"],
        name: "Instituto Tecnológico de Occidente del Estado de Hidalgo",
        alpha_two_code: "MX",
        domains: ["itsoeh.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.anahuac.mx/"],
        name: "Universidad Anáhuac",
        alpha_two_code: "MX",
        domains: ["anahuac.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://bajio.delasalle.edu.mx/"],
        name: "Universidad de La Salle, Bajío",
        alpha_two_code: "MX",
        domains: ["bajio.delasalle.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.buap.mx/"],
        name: "Benemerita Universidad Autónoma de Puebla",
        alpha_two_code: "MX",
        domains: ["buap.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.campusleon.ugto.mx/"],
        name: "Universidad de Guanajuato, Campus León",
        alpha_two_code: "MX",
        domains: ["campusleon.ugto.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ceti.mx/"],
        name: "Centro de Enseñanza Técnica Industrial",
        alpha_two_code: "MX",
        domains: ["ceti.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.cetys.mx/"],
        name: "CETYS Universidad",
        alpha_two_code: "MX",
        domains: ["cetys.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ceu.edu.mx/"],
        name: "Centro de Estudios Universitarios Monterrey",
        alpha_two_code: "MX",
        domains: ["ceu.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ceunix.com.mx/"],
        name: "Centro Universitario Ixtlahuaca",
        alpha_two_code: "MX",
        domains: ["ceunix.com.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ceux.mx/"],
        name: "Centro de Estudios Universitarios Xochicalco",
        alpha_two_code: "MX",
        domains: ["ceux.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.champagnat.edu.mx/"],
        name: "Universidad Champagnat",
        alpha_two_code: "MX",
        domains: ["champagnat.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.chapingo.mx/"],
        name: "Universidad Autónoma de Chapingo",
        alpha_two_code: "MX",
        domains: ["chapingo.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.colmex.mx/"],
        name: "El Colegio de México",
        alpha_two_code: "MX",
        domains: ["colmex.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.cuauhtemoc.edu.mx/"],
        name: "Universidad Cuauhtémoc",
        alpha_two_code: "MX",
        domains: ["cuauhtemoc.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://cueyatl.uam.mx/"],
        name: "Universidad Autónoma Metropolitana - Xochimilco",
        alpha_two_code: "MX",
        domains: ["cueyatl.uam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.dgit.gob.mx/"],
        name: "Dirección General de Institutos Tecnológicos",
        alpha_two_code: "MX",
        domains: ["dgit.gob.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ebc.mx/"],
        name: "Escuela Bancaria y Comercial",
        alpha_two_code: "MX",
        domains: ["ebc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.enes.unam.mx/"],
        name: "Escuela Nacional de Estudios Superiores Unidad León",
        alpha_two_code: "MX",
        domains: ["enes.unam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.frayluca.edu.mx/"],
        name: "Universidad Fray Luca Paccioli",
        alpha_two_code: "MX",
        domains: ["frayluca.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://hispano.edu.mx/"],
        name: "Universidad Hispanoamericana",
        alpha_two_code: "MX",
        domains: ["hispano.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.i.edu.mx/"],
        name: "Universidad Itaca",
        alpha_two_code: "MX",
        domains: ["i.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ipn.edu.mx/"],
        name: "Instituto Politécnico Nacional",
        alpha_two_code: "MX",
        domains: ["ipn.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itam.mx/"],
        name: "Instituto Tecnológico Autonómo de México",
        alpha_two_code: "MX",
        domains: ["itam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ita.mx/"],
        name: "Instituto Tecnológico de Aguascalientes",
        alpha_two_code: "MX",
        domains: ["ita.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itc.mx/"],
        name: "Instituto Tecnológico de Celaya",
        alpha_two_code: "MX",
        domains: ["itc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itdurango.edu.mx/"],
        name: "Instituto Tecnologico de Durango",
        alpha_two_code: "MX",
        domains: ["itdurango.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itesm.mx/"],
        name:
            "Instituto Tecnológico y de Estudios Superiores de Monterrey (ITESM)",
        alpha_two_code: "MX",
        domains: ["itesm.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.iteso.mx/"],
        name: "Instituto Tecnológico y de Estudios Superiores de Occidente",
        alpha_two_code: "MX",
        domains: ["iteso.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itleon.edu.mx/"],
        name: "Instituto Tecnológico de León",
        alpha_two_code: "MX",
        domains: ["itleon.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itmina.edu.mx/"],
        name: "Instituto Tecnologico de Minatitlan",
        alpha_two_code: "MX",
        domains: ["itmina.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itmorelia.edu.mx/"],
        name: "Instituto Tecnológico de Morelia",
        alpha_two_code: "MX",
        domains: ["itmorelia.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itq.edu.mx/"],
        name: "Instituto Tecnológico de Querétaro",
        alpha_two_code: "MX",
        domains: ["itq.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itslp.edu.mx/"],
        name: "Instituto Tecnológico de San Luis Potosí",
        alpha_two_code: "MX",
        domains: ["itslp.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itson.mx/"],
        name: "Instituto Tecnológico de Sonora",
        alpha_two_code: "MX",
        domains: ["itson.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.iztapalapa.uam.mx/"],
        name: "Universidad Autónoma Metropolitana - Iztapalapa",
        alpha_two_code: "MX",
        domains: ["iztapalapa.uam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.lef.upn.mx/"],
        name: "Universidad Pedagógica Nacional, Unidad León",
        alpha_two_code: "MX",
        domains: ["lef.upn.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.leon.uia.mx/"],
        name: "Universidad Iberoamericana, Campus León",
        alpha_two_code: "MX",
        domains: ["leon.uia.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://members.rotfl.com/uvp/"],
        name: "Universidad del Valle de Puebla",
        alpha_two_code: "MX",
        domains: ["members.rotfl.com"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.motolinia.com.mx/"],
        name: "Universidad Motolinía del Pedregal",
        alpha_two_code: "MX",
        domains: ["motolinia.com.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.olmeca.edu.mx/"],
        name: "Universidad Olmeca",
        alpha_two_code: "MX",
        domains: ["olmeca.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.poligto.edu.mx/"],
        name: "Politécnico de Guanajuato",
        alpha_two_code: "MX",
        domains: ["poligto.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.reduaeh.mx/"],
        name: "Universidad Autónoma del Estado de Hidalgo",
        alpha_two_code: "MX",
        domains: ["reduaeh.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.reduaz.mx/"],
        name: "Universidad Autónoma de Zacatecas",
        alpha_two_code: "MX",
        domains: ["reduaz.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.secupv.org/"],
        name: "Universidad Pedagógica Veracruzana",
        alpha_two_code: "MX",
        domains: ["secupv.org"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.tecbc.mx/"],
        name: "Tecnologico de Baja California, Universidad",
        alpha_two_code: "MX",
        domains: ["tecbc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.tepeyac.edu.mx/"],
        name: "Universidad del Tepeyac",
        alpha_two_code: "MX",
        domains: ["tepeyac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ties.com.mx/"],
        name: "Instituto de Estudios Superiores de la Sierra",
        alpha_two_code: "MX",
        domains: ["ties.com.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaaan.mx/"],
        name: 'Universidad Autónoma Agraria "Antonio Narro"',
        alpha_two_code: "MX",
        domains: ["uaaan.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaa.mx:8001/"],
        name: "Universidad Autónoma de Aguascalientes",
        alpha_two_code: "MX",
        domains: ["uaa.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uabc.mx/"],
        name: "Universidad Autónoma de Baja California",
        alpha_two_code: "MX",
        domains: ["uabc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uabcs.mx/"],
        name: "Universidad Autónoma de Baja California Sur",
        alpha_two_code: "MX",
        domains: ["uabcs.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uabjo.mx/"],
        name: 'Universidad Autónoma "Benito Juárez" de Oaxaca',
        alpha_two_code: "MX",
        domains: ["uabjo.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uacam.mx/"],
        name: "Universidad Autónoma de Campeche",
        alpha_two_code: "MX",
        domains: ["uacam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uach.mx/"],
        name: "Universidad Autónoma de Chihuahua",
        alpha_two_code: "MX",
        domains: ["uach.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://itsncg.edu.mx/"],
        name: "Instituto Tecnológico Superior de Nuevo Casas Grandes",
        alpha_two_code: "MX",
        domains: ["itsncg.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uacj.mx/"],
        name: "Universidad Autónoma de Ciudad Juárez",
        alpha_two_code: "MX",
        domains: ["uacj.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uacm.edu.mx/"],
        name: "Universidad Autónoma de la Ciudad de México",
        alpha_two_code: "MX",
        domains: ["uacm.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uadec.mx/"],
        name: "Universidad Autónoma de Coahuila",
        alpha_two_code: "MX",
        domains: ["uadec.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uad.edu.mx/"],
        name: "Universidad Autonoma  de Durango",
        alpha_two_code: "MX",
        domains: ["uad.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uady.mx/"],
        name: "Universidad Autónoma de Yucatán",
        alpha_two_code: "MX",
        domains: ["uady.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaed.edu.mx/"],
        name: "Universidad Autonoma España de Durango",
        alpha_two_code: "MX",
        domains: ["uaed.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaemex.mx/"],
        name: "Universidad Autónoma del Estado de México",
        alpha_two_code: "MX",
        domains: ["uaemex.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaem.mx/"],
        name: "Universidad Autónoma del Estado de Morelos",
        alpha_two_code: "MX",
        domains: ["uaem.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaf.mx/"],
        name: "Universidad Autónoma de Fresnillo",
        alpha_two_code: "MX",
        domains: ["uaf.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uag.mx/"],
        name: "Universidad Autónoma de Guadalajara",
        alpha_two_code: "MX",
        domains: ["uag.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uagro.mx/"],
        name: "Universidad Autónoma de Guerrero",
        alpha_two_code: "MX",
        domains: ["uagro.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ual.mx/"],
        name: "Universidad Autónoma de la Laguna",
        alpha_two_code: "MX",
        domains: ["ual.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uam.mx/"],
        name: "Universidad Autónoma Metropolitana",
        alpha_two_code: "MX",
        domains: ["uam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uane.edu.mx/"],
        name: "Universidad Autónoma del Noreste",
        alpha_two_code: "MX",
        domains: ["uane.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uanl.mx/"],
        name: "Universidad Autónoma de Nuevo León",
        alpha_two_code: "MX",
        domains: ["uanl.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uan.mx/"],
        name: "Universidad Autónoma de Nayarit",
        alpha_two_code: "MX",
        domains: ["uan.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaq.mx/"],
        name: "Universidad Autónoma de Querétaro",
        alpha_two_code: "MX",
        domains: ["uaq.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uaslp.mx/"],
        name: "Universidad Autónoma de San Luis Potosí",
        alpha_two_code: "MX",
        domains: ["uaslp.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uas.mx/"],
        name: "Universidad Anáhuac del Sur",
        alpha_two_code: "MX",
        domains: ["uas.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uasnet.mx/"],
        name: "Universidad Autónoma de Sinaloa",
        alpha_two_code: "MX",
        domains: ["uasnet.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uat.mx/"],
        name: "Universidad Autónoma de Tamaulipas",
        alpha_two_code: "MX",
        domains: ["uat.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uatx.mx/"],
        name: "Universidad Autónoma de Tlaxcala",
        alpha_two_code: "MX",
        domains: ["uatx.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ubac.edu.mx/"],
        name: "Universidad del Bajío",
        alpha_two_code: "MX",
        domains: ["ubac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ucem.edu.mx/"],
        name: "Universidad del Centro de México",
        alpha_two_code: "MX",
        domains: ["ucem.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uclah.edu.mx/"],
        name: "Universidad Cientifica Latinoamericana de Hidalgo",
        alpha_two_code: "MX",
        domains: ["uclah.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ucol.mx/"],
        name: "Universidad de Colima",
        alpha_two_code: "MX",
        domains: ["ucol.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udec.edu.mx/"],
        name: "Universidad de Celaya",
        alpha_two_code: "MX",
        domains: ["udec.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udeci.edu.mx/"],
        name: "Universidad de Cuautitlan Izcalli",
        alpha_two_code: "MX",
        domains: ["udeci.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udeh.edu.mx/"],
        name: "Universidad de Hermosillo",
        alpha_two_code: "MX",
        domains: ["udeh.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udem.edu.mx/"],
        name: "Universidad de Monterrey",
        alpha_two_code: "MX",
        domains: ["udem.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udesanmiguel.edu.mx/"],
        name: "Universidad de San Miguel",
        alpha_two_code: "MX",
        domains: ["udesanmiguel.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udg.mx/"],
        name: "Universidad de Guadalajara",
        alpha_two_code: "MX",
        domains: ["udg.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udla.mx/"],
        name: "Universidad de las Américas",
        alpha_two_code: "MX",
        domains: ["udla.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udlap.mx/"],
        name: "Universidad de las Américas - Puebla",
        alpha_two_code: "MX",
        domains: ["udlap.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udo.mx/"],
        name: "Universidad de Occidente",
        alpha_two_code: "MX",
        domains: ["udo.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.udv.edu.mx/"],
        name: "Universidad Don Vasco",
        alpha_two_code: "MX",
        domains: ["udv.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ufm.edu.mx/"],
        name: "Universidad Franciscana de México",
        alpha_two_code: "MX",
        domains: ["ufm.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ufram.edu.mx/"],
        name: "Universidad Franco-Mexicana",
        alpha_two_code: "MX",
        domains: ["ufram.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ugto.mx/"],
        name: "Universidad de Guanajuato",
        alpha_two_code: "MX",
        domains: ["ugto.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uia.mx/"],
        name: "Universidad Iberoamericana",
        alpha_two_code: "MX",
        domains: ["uia.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uic.edu.mx/"],
        name: "Universidad Intercontinental",
        alpha_two_code: "MX",
        domains: ["uic.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uileon.edu.mx/"],
        name: "Universidad Insurgentes Plantel León",
        alpha_two_code: "MX",
        domains: ["uileon.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ujat.mx/"],
        name: "Universidad Juárez Autónoma de Tabasco",
        alpha_two_code: "MX",
        domains: ["ujat.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ujed.mx/"],
        name: "Universidad Juárez del Estado de Durango",
        alpha_two_code: "MX",
        domains: ["ujed.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ujsierra.mx/"],
        name: "Universidad Justo Sierra",
        alpha_two_code: "MX",
        domains: ["ujsierra.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ula.edu.mx/"],
        name: "Universidad Latinoamericana",
        alpha_two_code: "MX",
        domains: ["ula.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ulsab.edu.mx/"],
        name: "Universidad Lasallista Benavente",
        alpha_two_code: "MX",
        domains: ["ulsab.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ulsac.edu.mx/"],
        name: "Universidad La Salle Cuernavaca",
        alpha_two_code: "MX",
        domains: ["ulsac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ulsa.edu.mx/"],
        name: "Universidad La Salle",
        alpha_two_code: "MX",
        domains: ["ulsa.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umad.edu.mx/"],
        name: "Universidad Madero",
        alpha_two_code: "MX",
        domains: ["umad.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uman.edu.mx/"],
        name: "Universidad México Americana del Norte",
        alpha_two_code: "MX",
        domains: ["uman.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umar.mx/"],
        name: "Universidad del Mar",
        alpha_two_code: "MX",
        domains: ["umar.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umich.mx/"],
        name: "Universidad Michoacana de San Nicolás de Hidalgo",
        alpha_two_code: "MX",
        domains: ["umich.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umi.edu.mx/"],
        name: "Universidad México Internacional",
        alpha_two_code: "MX",
        domains: ["umi.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umla.edu.mx/"],
        name: "Universidad Metropolitana Latin Campus",
        alpha_two_code: "MX",
        domains: ["umla.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umm.edu.mx/"],
        name: "Universidad Metropolitana de Monterrey",
        alpha_two_code: "MX",
        domains: ["umm.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umne.edu.mx/"],
        name: "Universidad Mexicana del Noreste",
        alpha_two_code: "MX",
        domains: ["umne.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umontemorelos.edu.mx/"],
        name: "Universidad de Montemorelos",
        alpha_two_code: "MX",
        domains: ["umontemorelos.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.umsa.edu.mx/"],
        name: "Universidad Mesoamericana de San Agustín",
        alpha_two_code: "MX",
        domains: ["umsa.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unacar.mx/"],
        name: "Universidad Autónoma del Carmen",
        alpha_two_code: "MX",
        domains: ["unacar.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unach.mx/"],
        name: "Universidad Autónoma de Chiapas",
        alpha_two_code: "MX",
        domains: ["unach.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unam.mx/"],
        name: "Universidad Nacional Autónoma de México",
        alpha_two_code: "MX",
        domains: ["unam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.un.edu.mx/"],
        name: "Universidad del Norte",
        alpha_two_code: "MX",
        domains: ["un.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.une.edu.mx/"],
        name: "Universidad del Noreste",
        alpha_two_code: "MX",
        domains: ["une.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unes.edu.mx/"],
        name: "Universidad España de Durango",
        alpha_two_code: "MX",
        domains: ["unes.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unicach.edu.mx/"],
        name: "Universidad de Ciencias y Artes de Chiapas",
        alpha_two_code: "MX",
        domains: ["unicach.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unica.edu.mx/"],
        name: "Universidad de Comunicación Avanzada",
        alpha_two_code: "MX",
        domains: ["unica.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unikino.mx/"],
        name: "Universidad Kino",
        alpha_two_code: "MX",
        domains: ["unikino.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unimayab.edu.mx/"],
        name: "Universidad del Mayab",
        alpha_two_code: "MX",
        domains: ["unimayab.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unimex.edu.mx/"],
        name: "Universidad Mexicana",
        alpha_two_code: "MX",
        domains: ["unimex.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unitec.mx/"],
        name: "Universidad Tecnológica de México",
        alpha_two_code: "MX",
        domains: ["unitec.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.univa.mx/"],
        name: "Universidad del Valle de Atemajac",
        alpha_two_code: "MX",
        domains: ["univa.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.univas.edu.mx/"],
        name: "Universidad Jóse Vasconcelos",
        alpha_two_code: "MX",
        domains: ["univas.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.univchapultepec.edu.mx/"],
        name: "Universidad Chapultepéc",
        alpha_two_code: "MX",
        domains: ["univchapultepec.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.universidaddeleon.edu.mx/"],
        name: "Universidad de León",
        alpha_two_code: "MX",
        domains: ["universidaddeleon.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.universidadlaconcordia.edu.mx/"],
        name: "Universidad la Concordia",
        alpha_two_code: "MX",
        domains: ["universidadlaconcordia.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.universidadmotolinia.edu.mx/"],
        name: "Universidad Motolinía del Pedegral",
        alpha_two_code: "MX",
        domains: ["universidadmotolinia.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.universidadsalesiana.edu.mx/"],
        name: "Universidad Salesiana",
        alpha_two_code: "MX",
        domains: ["universidadsalesiana.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.univillarica.mx/"],
        name: "Universidad Autónoma de Veracruz Villa Rica",
        alpha_two_code: "MX",
        domains: ["univillarica.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unla.edu.mx/"],
        name: "Universidad Latina",
        alpha_two_code: "MX",
        domains: ["unla.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.un.mx/"],
        name: "Universidad de Norteamerica",
        alpha_two_code: "MX",
        domains: ["un.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uno.mx/"],
        name: "Universidad del Noroeste",
        alpha_two_code: "MX",
        domains: ["uno.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.unum.edu.mx/"],
        name: "Universidad Nuevo Mundo",
        alpha_two_code: "MX",
        domains: ["unum.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uom.edu.mx/"],
        name: "Universidad Obrera de Mexico",
        alpha_two_code: "MX",
        domains: ["uom.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.upaep.mx/"],
        name: "Universidad Popular Autonóma del Estado de Puebla",
        alpha_two_code: "MX",
        domains: ["upaep.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.upiig.ipn.mx/"],
        name: "Instituto Politécnico Nacional, Campus Guanajuato",
        alpha_two_code: "MX",
        domains: ["upiig.ipn.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.up.mx/"],
        name: "Universidad Panamericana",
        alpha_two_code: "MX",
        domains: ["up.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.upn.mx/"],
        name: "Universidad Pedagógica Nacional",
        alpha_two_code: "MX",
        domains: ["upn.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uqroo.mx/"],
        name: "Universidad de Quintana Roo",
        alpha_two_code: "MX",
        domains: ["uqroo.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.urmh.edu.mx/"],
        name: "Universidad Regional Miguel Hidalgo",
        alpha_two_code: "MX",
        domains: ["urmh.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ur.mx/"],
        name: "Universidad Regiomontana",
        alpha_two_code: "MX",
        domains: ["ur.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.urse.edu.mx/"],
        name: "Universidad Regional del Sureste",
        alpha_two_code: "MX",
        domains: ["urse.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.usac.edu.mx/"],
        name: "Universidad de la Sierra A.C.",
        alpha_two_code: "MX",
        domains: ["usac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.usb.edu.mx/"],
        name: "Universidad Simón Bolivar",
        alpha_two_code: "MX",
        domains: ["usb.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.usf.com.mx/"],
        name: "Universidad Santa Fe",
        alpha_two_code: "MX",
        domains: ["usf.com.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uson.mx/"],
        name: "Universidad de Sonora",
        alpha_two_code: "MX",
        domains: ["uson.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.utm.mx/"],
        name: "Universidad Tecnologica de la Mixteca",
        alpha_two_code: "MX",
        domains: ["utm.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.utneza.edu.mx/"],
        name: "Universidad Tecnologica de Nezahualcoyotl",
        alpha_two_code: "MX",
        domains: ["utneza.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uvb.edu.mx/"],
        name: "Universidad del Valle del Bravo",
        alpha_two_code: "MX",
        domains: ["uvb.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uvg1.net/"],
        name: "Universidad Valle del Grijalva",
        alpha_two_code: "MX",
        domains: ["uvg1.net"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uvmnet.edu/"],
        name: "Universidad del Valle de México",
        alpha_two_code: "MX",
        domains: ["uvmnet.edu"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uv.mx/"],
        name: "Universidad Veracruzana",
        alpha_two_code: "MX",
        domains: ["uv.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uvt.edu.mx/"],
        name: "Universidad del Valle de Toluca",
        alpha_two_code: "MX",
        domains: ["uvt.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.uxac.edu.mx/"],
        name: "Universidad Xicotepetl",
        alpha_two_code: "MX",
        domains: ["uxac.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.ver.ucc.mx/"],
        name: "Universidad Cristóbal Colón",
        alpha_two_code: "MX",
        domains: ["ver.ucc.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.westhill.edu.mx/"],
        name: "Westhill University",
        alpha_two_code: "MX",
        domains: ["westhill.edu.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["https://azc.uam.mx/"],
        name: "Universidad Autónoma Metropolitana - Azcapotzalco",
        alpha_two_code: "MX",
        domains: ["azc.uam.mx"],
    },
    {
        "state-province": null,
        country: "Mexico",
        web_pages: ["http://www.itsoeh.edu.mx/"],
        name: "Instituto Tecnológico de Occidente del Estado de Hidalgo",
        alpha_two_code: "MX",
        domains: ["itsoeh.edu.mx"],
    },
];

export default data;
